### ISSUE TITLE
Minor rotation issue

### ISSUE THREAD

**Issue by ServicePal** [lucabecchetti/InAppNotify#1]
Nice work Luca.
While you have support for rotation, I noticed that the textView does not size to max width of the screen, when you rotate the iPad, _while_ the notification is displayed. 

IF you go from Landscapre to Portrait that will cause the Send button to hide.
![landscape](https://user-images.githubusercontent.com/8471863/31524857-2143501e-af71-11e7-8cfd-872e3ff03ee7.png)
![portrait](https://user-images.githubusercontent.com/8471863/31524858-21680daa-af71-11e7-8300-bc158df13cf2.png)

**Comment by lucabecchetti** [comment]
hi @ServicePal thanks for your feedback... i didn't test it on the iPad! i have to do some test...

**Comment by lucabecchetti** [comment]
Ok... there's a strange bug in iPad, when receive rotation notification the size didn't change, I think it is solved now, please update your pod!
