### ISSUE TITLE
Notification view clips on iPhone X

### ISSUE THREAD

**Issue by richardtop** [lucabecchetti/InAppNotify#3]
The problem occurs on the iPhone X only, here is the screenshot: 

![image](https://user-images.githubusercontent.com/8013017/32075715-487baeb6-baa6-11e7-871d-e877b542f294.png)

The notification view is being clipped by the iPhone bezel.

**Comment by lucabecchetti** [comment]
Thanks... i have to test it on iphoneX

**Comment by ServicePal** [comment]
Surely, the new Status bar height have broken many apps
print(UIApplication.shared .statusBarFrame.height)
44.0 Portrait
0.0 Landscape on iPhone X

**Comment by MohmmadSawalha-ios** [comment]
Any updates on this issue guys
