### ISSUE TITLE
How can I display my APNS notification with InAppNotify while in app?

### ISSUE THREAD

**Issue by uetcis** [lucabecchetti/InAppNotify#4]
Hello! 
Recently, I installed InAppNotify and tried to use it to handle the function 'didReceiveRemoteNotification' like this in AppDelegate :

```swift
    func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any]) {
        guard let vc = PresentingViewController.shared, // A special way to get the presenting vc
        let content = userInfo["aps"] as? [String:Any],
        let alert = content["alert"] as? [String:String],
        let title = alert["title"],
        let subTitle = alert["subtitle"],
        let imageUrl = alert["image"] else { return }
        let announcement = Announcement(title: title, subtitle: subTitle, image: nil, urlImage: imageUrl, duration: 3, interactionType: .none, userInfo: nil, action: nil)
        InAppNotify.Show(announcement, to: vc)
    }
```

However, the notify isn't showed after this, could you please help me find out my mistakes?

**Comment by lucabecchetti** [comment]
Hi, try to launch show command in main thread with: DispatchQueue.main.async{  
Show code here 
  }

**Comment by uetcis** [comment]
It works now, thank you so much!

**Comment by lucabecchetti** [comment]
If you want... share the name of your project! bye!

**Comment by uetcis** [comment]
No problem, and it's my honor to do so :)
You can checkout my project at here [BirthReminder](https://captainyukinoshitahachiman.github.io/BirthReminder/)
It's actually not on the App Store yet, but you can try it through TestFlight now
😄

**Comment by lucabecchetti** [comment]
I added to README! thanks! have a good work!

**Comment by uetcis** [comment]
Thank you, the same to you 😆
