### ISSUE TITLE
Argument of '#selector' refers to instance method that is not exposed to Objective-C

### ISSUE THREAD

**Issue by mariohercules** [lucabecchetti/InAppNotify#5]
- Argument of '#selector' refers to instance method 'orientationDidChange()' that is not exposed to Objective-C
- Argument of '#selector' refers to instance method 'displayTimerDidFire()' that is not exposed to Objective-C

Add '@objc' to expose this instance method to Objective-C

**Comment by lucabecchetti** [comment]
fixed in last commit!

**Comment by olcayertas** [comment]
Still gettin the same error.

**Comment by olcayertas** [comment]
Try: `pod 'InAppNotify', git: 'https://github.com/lucabecchetti/InAppNotify.git', commit: 'HEAD'`
Please update podspec.
